./scripts/deleteTTKmodule.sh AbstractMorseSmaleComplex
./scripts/deleteTTKmodule.sh BottleneckDistance
./scripts/deleteTTKmodule.sh CellDataConverter
./scripts/deleteTTKmodule.sh CellDataSelector
./scripts/deleteTTKmodule.sh CinemaImaging
./scripts/deleteTTKmodule.sh CinemaLayout
./scripts/deleteTTKmodule.sh CinemaProductReader
./scripts/deleteTTKmodule.sh CinemaQuery
./scripts/deleteTTKmodule.sh CinemaReader
./scripts/deleteTTKmodule.sh CinemaWriter
./scripts/deleteTTKmodule.sh ComponentSize
./scripts/deleteTTKmodule.sh ContinuousScatterPlot
./scripts/deleteTTKmodule.sh ContourForests
./scripts/deleteTTKmodule.sh ContourForestsTree
./scripts/deleteTTKmodule.sh ContourTree
./scripts/deleteTTKmodule.sh CreateMultiBlockDataSet
./scripts/deleteTTKmodule.sh CrossDissolvePersistenceDiagrams
./scripts/deleteTTKmodule.sh DataSetInterpolator
./scripts/deleteTTKmodule.sh DataSetToTable
./scripts/deleteTTKmodule.sh DepthImageBasedGeometryApproximation
./scripts/deleteTTKmodule.sh DimensionReduction
./scripts/deleteTTKmodule.sh DiscreteGradient
./scripts/deleteTTKmodule.sh DistanceField
./scripts/deleteTTKmodule.sh EndFor
./scripts/deleteTTKmodule.sh ForEachRow
./scripts/deleteTTKmodule.sh Fiber
./scripts/deleteTTKmodule.sh FiberSurface
./scripts/deleteTTKmodule.sh FTMTree
./scripts/deleteTTKmodule.sh FtmTreePP
./scripts/deleteTTKmodule.sh GeometrySmoother
./scripts/deleteTTKmodule.sh GradientForPH
./scripts/deleteTTKmodule.sh IcoSphere
./scripts/deleteTTKmodule.sh ImportEmbeddingFromTable
./scripts/deleteTTKmodule.sh IntegralLines
./scripts/deleteTTKmodule.sh JacobiSet
./scripts/deleteTTKmodule.sh LDistance
./scripts/deleteTTKmodule.sh LowestCommonAncestor
./scripts/deleteTTKmodule.sh MandatoryCriticalPoints
./scripts/deleteTTKmodule.sh ManifoldCheck
./scripts/deleteTTKmodule.sh MapFunctionTo3D
./scripts/deleteTTKmodule.sh MeshSubdivision
./scripts/deleteTTKmodule.sh MorseSmaleComplex
./scripts/deleteTTKmodule.sh MorseSmaleComplex2D
./scripts/deleteTTKmodule.sh MorseSmaleComplex3D
./scripts/deleteTTKmodule.sh MultifieldComparisonMeasure
./scripts/deleteTTKmodule.sh MultivariateGradient
./scripts/deleteTTKmodule.sh ndPersistentHomology
./scripts/deleteTTKmodule.sh PersistenceCurve
./scripts/deleteTTKmodule.sh PersistenceDiagram
./scripts/deleteTTKmodule.sh PersistentHomology
./scripts/deleteTTKmodule.sh PointDataConverter
./scripts/deleteTTKmodule.sh PointDataSelector
./scripts/deleteTTKmodule.sh PointMerger
./scripts/deleteTTKmodule.sh ProjectionFromField
./scripts/deleteTTKmodule.sh RangeDrivenOctree
./scripts/deleteTTKmodule.sh RangeMinimumQuery
./scripts/deleteTTKmodule.sh RangePolygon
./scripts/deleteTTKmodule.sh ReebSpace
./scripts/deleteTTKmodule.sh ScalarFieldCriticalPoints
./scripts/deleteTTKmodule.sh ScalarFieldNormalizer
./scripts/deleteTTKmodule.sh ScalarFieldSmoother
./scripts/deleteTTKmodule.sh SphereFromPoint
./scripts/deleteTTKmodule.sh TableDataSelector
./scripts/deleteTTKmodule.sh TopologicalCompression
./scripts/deleteTTKmodule.sh TopologicalCompressionReader
./scripts/deleteTTKmodule.sh TopologicalCompressionWriter
./scripts/deleteTTKmodule.sh TopologicalSimplification
./scripts/deleteTTKmodule.sh TrackingFromFields
./scripts/deleteTTKmodule.sh TrackingFromOverlap
./scripts/deleteTTKmodule.sh TrackingFromPersistenceDiagrams
./scripts/deleteTTKmodule.sh TriangulationRequest
./scripts/deleteTTKmodule.sh UncertainDataEstimator
./scripts/deleteTTKmodule.sh WRLExporter